/**
 * vite-plugin-axe-metadata
 *
 * Replaces two Grunt tasks:
 *   1. metadata-function-map — scans check/rule TS files, generates import map
 *   2. configure — reads rule/check/misc JSON, compiles doT templates, generates config
 *
 * Generated files:
 *   - lib/core/base/metadata-function-map.ts  (import map for check/rule functions)
 *   - lib/core/generated/default-config.ts    (pre-compiled configuration blob)
 *   - doc/rule-descriptions.md                (markdown table of all rules)
 */

import { type Plugin } from 'vite';
import { globSync } from 'glob';
import * as path from 'node:path';
import * as fs from 'node:fs';
import { encode } from 'html-entities';

// Use posix paths for consistency in generated import statements
const posixPath = path.posix;

// ---------------------------------------------------------------------------
// doT template support
// ---------------------------------------------------------------------------

// eslint-disable-next-line @typescript-eslint/no-require-imports
const doT = require('@deque/dot');

// Sync with lib/core/imports/index.js — prevent stripping newlines
doT.templateSettings.strip = false;

const doTRegex = /\{\{.+?\}\}/g;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function toTitleCase(str: string): string {
  return str.replace(/-\w/g, txt => {
    return txt.charAt(1)!.toUpperCase() + txt.substring(2).toLowerCase();
  });
}

function makeHeaderLink(title: string): string {
  return title
    .replace(/ /g, '-')
    .replace(/[.&]/g, '')
    .toLowerCase();
}

// ---------------------------------------------------------------------------
// Part 1: metadata-function-map generation
// ---------------------------------------------------------------------------

function generateMetadataFunctionMap(axeCoreRoot: string): string {
  const srcGlobs = [
    'lib/checks/**/*-{evaluate,after}.ts',
    'lib/rules/**/*-matches.ts'
  ];

  const destFile = path.join(
    axeCoreRoot,
    'lib/core/base/metadata-function-map.ts'
  );
  const destDir = path.dirname(destFile);

  const map: Record<string, string> = {};
  let outFile =
    '// This file is automatically generated using vite-plugin-axe-metadata\n';

  for (const globPattern of srcGlobs) {
    const files = globSync(globPattern, {
      cwd: axeCoreRoot,
      posix: true
    });
    for (const filePath of files) {
      const ext = posixPath.extname(filePath);
      const relativePath = posixPath
        .relative(
          posixPath.dirname(
            posixPath.relative(
              axeCoreRoot,
              destDir.split(path.sep).join('/')
            )
          ) || '.',
          filePath
        )
        .replace(/\.[jt]s$/, '');

      // Compute relative from destDir to the file
      const absFile = path.join(axeCoreRoot, filePath);
      let rel = path
        .relative(destDir, absFile)
        .split(path.sep)
        .join('/');
      rel = rel.replace(/\.[jt]s$/, '');
      if (!rel.startsWith('.')) {
        rel = './' + rel;
      }

      const filename = posixPath.basename(filePath, ext);
      const functionName = toTitleCase(filename);

      outFile += `import ${functionName} from '${rel}';\n`;
      map[filename] = functionName;
    }
  }

  outFile += `\nconst metadataFunctionMap = {\n`;
  outFile += Object.keys(map)
    .sort()
    .map(key => `  '${key}': ${map[key]}`)
    .join(',\n');
  outFile += `\n};\n\nexport default metadataFunctionMap;\n`;

  return outFile;
}

// ---------------------------------------------------------------------------
// Part 2: configuration generation
// ---------------------------------------------------------------------------

interface CheckJson {
  id: string;
  evaluate?: string;
  after?: string;
  options?: unknown;
  metadata?: {
    impact?: string;
    messages?: Record<string, unknown>;
  };
  [key: string]: unknown;
}

interface RuleJson {
  id: string;
  impact?: string;
  matches?: string;
  tags: string[];
  actIds?: string[];
  metadata?: {
    description?: string;
    help?: string;
  };
  any: (string | { id: string; options?: unknown })[];
  all: (string | { id: string; options?: unknown })[];
  none: (string | { id: string; options?: unknown })[];
  reviewOnFail?: boolean;
  enabled?: boolean;
  [key: string]: unknown;
}

interface MiscJson {
  type?: string;
  metadata?: {
    failureMessage?: string;
  };
  incompleteFallbackMessage?: string;
}

interface DescriptionSection {
  title: string;
  intro?: string;
  rules: string[][];
}

const axeImpact = Object.freeze([
  'minor',
  'moderate',
  'serious',
  'critical'
]);

function readJsonFiles<T>(pattern: string, cwd: string): T[] {
  const files = globSync(pattern, { cwd, posix: true });
  return files.map(f => {
    const content = fs.readFileSync(path.join(cwd, f), 'utf-8');
    return JSON.parse(content) as T;
  });
}

function parseMetaData(
  source: { metadata?: Record<string, unknown>; id?: string; type?: string },
  propType: string,
  locale?: LocaleData
): Record<string, unknown> {
  let data = source.metadata;
  const id = source.id || source.type;

  // Apply locale translations for rules and failureSummaries (checks handled separately)
  if (id && locale && propType !== 'checks') {
    const localeSection = (locale as unknown as Record<string, unknown>)[propType] as
      | Record<string, unknown>
      | undefined;
    if (localeSection && localeSection[id]) {
      data = localeSection[id] as Record<string, unknown>;
    }
  }

  const result: Record<string, unknown> = data ? structuredClone(data) : {};

  if (result.messages) {
    const messages = result.messages as Record<string, unknown>;
    for (const key of Object.keys(messages)) {
      if (
        typeof messages[key] !== 'object' &&
        typeof messages[key] === 'string' &&
        doTRegex.test(messages[key] as string)
      ) {
        messages[key] = doT.template(messages[key] as string).toString();
      }
    }
  }
  if (
    result.failureMessage &&
    typeof result.failureMessage === 'string' &&
    doTRegex.test(result.failureMessage)
  ) {
    result.failureMessage = doT
      .template(result.failureMessage as string)
      .toString();
  }
  return result;
}

function findCheck(
  checkCollection: CheckJson[],
  id: string
): CheckJson | undefined {
  return checkCollection.find(c => c.id === id);
}

export interface LocaleData {
  lang: string;
  rules?: Record<string, Record<string, unknown>>;
  checks?: Record<string, Record<string, unknown>>;
  failureSummaries?: Record<string, Record<string, unknown>>;
  incompleteFallbackMessage?: string;
}

export function generateConfig(
  axeCoreRoot: string,
  locale?: LocaleData
): {
  configData: string;
  descriptions: string;
} {
  const packageJson = JSON.parse(
    fs.readFileSync(path.join(axeCoreRoot, 'package.json'), 'utf-8')
  );
  const axeVersion = packageJson.version.substring(
    0,
    packageJson.version.lastIndexOf('.')
  );

  // Read all definitions
  const rules = readJsonFiles<RuleJson>('lib/rules/**/*.json', axeCoreRoot);
  const checks = readJsonFiles<CheckJson>('lib/checks/**/*.json', axeCoreRoot);
  const misc = readJsonFiles<MiscJson>('lib/misc/**/*.json', axeCoreRoot);

  // Apply locale translations to checks before parsing (matches legacy configure.js)
  if (locale?.checks) {
    for (const check of checks) {
      if (locale.checks[check.id] && check.metadata) {
        check.metadata.messages = locale.checks[check.id] as Record<string, unknown>;
      }
    }
  }

  // Build metadata
  const metadata: {
    rules: Record<string, Record<string, unknown>>;
    checks: Record<string, Record<string, unknown>>;
    failureSummaries: Record<string, Record<string, unknown>>;
    incompleteFallbackMessage: string;
  } = {
    rules: {},
    checks: {},
    failureSummaries: {},
    incompleteFallbackMessage: ''
  };

  // Description sections for rule-descriptions.md
  const descriptionSections: Record<string, DescriptionSection> = {
    wcag20: {
      title: 'WCAG 2.0 Level A & AA Rules',
      rules: []
    },
    wcag21: {
      title: 'WCAG 2.1 Level A & AA Rules',
      rules: []
    },
    wcag22: {
      title: 'WCAG 2.2 Level A & AA Rules',
      intro:
        'These rules are disabled by default, until WCAG 2.2 is more widely adopted and required.',
      rules: []
    },
    bestPractice: {
      title: 'Best Practices Rules',
      intro:
        'Rules that do not necessarily conform to WCAG success criterion but are industry accepted practices that improve the user experience.',
      rules: []
    },
    wcag2aaa: {
      title: 'WCAG 2.x level AAA rules',
      intro:
        'Rules that check for conformance to WCAG AAA success criteria that can be fully automated. These are disabled by default in axe-core.',
      rules: []
    },
    experimental: {
      title: 'Experimental Rules',
      intro:
        'Rules we are still testing and developing. They are disabled by default in axe-core, but are enabled for the axe browser extensions.',
      rules: []
    },
    deprecated: {
      title: 'Deprecated Rules',
      intro:
        'Deprecated rules are disabled by default and will be removed in the next major release.',
      rules: []
    }
  };

  const descriptionTableHeader =
    '| Rule ID | Description | Impact | Tags | Issue Type | [ACT Rules](https://www.w3.org/WAI/standards-guidelines/act/rules/) |\n| :------- | :------- | :------- | :------- | :------- | :------- |\n';

  const TOC = Object.keys(descriptionSections)
    .map(key => {
      const section = descriptionSections[key]!;
      return `- [${section.title}](#${makeHeaderLink(section.title)})`;
    })
    .join('\n');

  // Parse checks metadata first
  function parseChecksFromCollection(
    checkRefs: (string | { id: string; options?: unknown })[]
  ): (string | { id: string; options?: unknown })[] {
    return checkRefs.map(check => {
      const id = typeof check === 'string' ? check : check.id;
      const definition = findCheck(checks, id);
      if (!definition) {
        console.warn(`check ${id} not found`);
        return check;
      }

      const c: { id: string; options?: unknown } = { id };
      const options =
        typeof check !== 'string' ? check.options : undefined;
      c.options = options ?? definition.options;

      if (definition.metadata && !metadata.checks[id]) {
        metadata.checks[id] = parseMetaData(definition, 'checks', locale);
      }

      return c.options === undefined ? id : c;
    });
  }

  // Traversal helpers for computing impact
  function traverseChecks<T>(
    checkCollection: (string | { id: string; options?: unknown })[],
    predicate: (definition: CheckJson | undefined, out: T) => T,
    startValue: T
  ): T {
    return checkCollection.reduce((out: T, check) => {
      const id = typeof check === 'string' ? check : check.id;
      const definition = findCheck(checks, id);
      return predicate(definition, out);
    }, startValue);
  }

  function capitalize(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1);
  }

  function parseImpactForRule(rule: RuleJson): string {
    if (rule.impact) {
      return capitalize(rule.impact);
    }

    function getImpactScores(
      definition: CheckJson | undefined,
      out: number[]
    ): number[] {
      if (definition?.metadata?.impact) {
        const impactScore = axeImpact.indexOf(definition.metadata.impact);
        out.push(impactScore);
      }
      return out;
    }

    function getScore(
      checkCollection: (string | { id: string; options?: unknown })[],
      onlyHighestScore: boolean
    ): number[] {
      const scores = traverseChecks(checkCollection, getImpactScores, []);
      if (scores.length) {
        return onlyHighestScore
          ? [Math.max(...scores)]
          : [...new Set(scores)];
      }
      return [];
    }

    const highestImpactForRuleTypeAny = getScore(rule.any, true);
    const allUniqueImpactsForRuleTypeAll = getScore(rule.all, false);
    const allUniqueImpactsForRuleTypeNone = getScore(rule.none, false);
    const cumulativeImpacts = highestImpactForRuleTypeAny
      .concat(allUniqueImpactsForRuleTypeAll)
      .concat(allUniqueImpactsForRuleTypeNone);
    const cumulativeScores = [...new Set(cumulativeImpacts)].sort();

    return cumulativeScores.reduce((out, cV) => {
      return out.length
        ? out + ', ' + capitalize(axeImpact[cV]!)
        : capitalize(axeImpact[cV]!);
    }, '');
  }

  function parseFailureForRule(rule: RuleJson): boolean {
    function hasFailure(
      definition: CheckJson | undefined,
      out: boolean
    ): boolean {
      if (
        !rule.reviewOnFail &&
        definition?.metadata?.impact
      ) {
        out = out || !!(definition.metadata.messages?.fail);
      }
      return out;
    }

    return (
      traverseChecks(rule.any, hasFailure, false) ||
      traverseChecks(rule.all, hasFailure, false) ||
      traverseChecks(rule.none, hasFailure, false)
    );
  }

  function parseIncompleteForRule(rule: RuleJson): boolean {
    function hasIncomplete(
      definition: CheckJson | undefined,
      out: boolean
    ): boolean {
      if (definition?.metadata?.impact) {
        out =
          out ||
          !!(definition.metadata.messages?.incomplete) ||
          !!rule.reviewOnFail;
      }
      return out;
    }

    return (
      traverseChecks(rule.any, hasIncomplete, false) ||
      traverseChecks(rule.all, hasIncomplete, false) ||
      traverseChecks(rule.none, hasIncomplete, false)
    );
  }

  function createActLinksForRule(rule: RuleJson): string {
    const actIds = rule.actIds || [];
    return actIds
      .map(id => `[${id}](https://act-rules.github.io/rules/${id})`)
      .join(', ');
  }

  // Process rules
  const processedRules = rules.map(rule => {
    const impact = parseImpactForRule(rule);
    const canFail = parseFailureForRule(rule);
    const canIncomplete = parseIncompleteForRule(rule);

    rule.any = parseChecksFromCollection(rule.any);
    rule.all = parseChecksFromCollection(rule.all);
    rule.none = parseChecksFromCollection(rule.none);

    if (rule.metadata && !metadata.rules[rule.id]) {
      metadata.rules[rule.id] = parseMetaData(rule, 'rules', locale);
    }

    // Determine which description section this rule belongs to
    let result: string[][];
    if (rule.tags.includes('deprecated')) {
      result = descriptionSections['deprecated']!.rules;
    } else if (rule.tags.includes('experimental')) {
      result = descriptionSections['experimental']!.rules;
    } else if (rule.tags.find(tag => tag.includes('aaa'))) {
      result = descriptionSections['wcag2aaa']!.rules;
    } else if (rule.tags.includes('best-practice')) {
      result = descriptionSections['bestPractice']!.rules;
    } else if (rule.tags.find(tag => tag.startsWith('wcag2a'))) {
      result = descriptionSections['wcag20']!.rules;
    } else if (rule.tags.find(tag => tag.startsWith('wcag21a'))) {
      result = descriptionSections['wcag21']!.rules;
    } else {
      result = descriptionSections['wcag22']!.rules;
    }

    const issueType: string[] = [];
    if (canFail) {
      issueType.push('failure');
    }
    if (canIncomplete) {
      issueType.push('needs&nbsp;review');
    }

    const actLinks = createActLinksForRule(rule);

    result.push([
      `[${rule.id}](https://dequeuniversity.com/rules/axe/${axeVersion}/${rule.id}?application=RuleDescription)`,
      encode(rule.metadata?.description ?? ''),
      impact,
      rule.tags.join(', '),
      issueType.join(', '),
      actLinks
    ]);

    return rule;
  });

  // Build failure summaries
  for (const summary of misc) {
    if (summary.type) {
      metadata.failureSummaries[summary.type] = parseMetaData(
        summary as { metadata?: Record<string, unknown> },
        'failureSummaries',
        locale
      );
    }
  }

  // Get incomplete fallback message
  const incompleteSummary = misc.find(
    m => typeof m.incompleteFallbackMessage === 'string'
  );
  metadata.incompleteFallbackMessage = locale?.incompleteFallbackMessage
    ?? (incompleteSummary ? incompleteSummary.incompleteFallbackMessage! : '');

  // Build the configuration blob
  // Remove 'metadata' key from rules and checks for the config
  // (metadata is stored separately in data.rules and data.checks)
  const blacklist = ['metadata'];
  const configBlob = {
    lang: locale?.lang ?? 'en',
    data: metadata,
    rules: processedRules,
    checks
  };

  const configJson = JSON.stringify(configBlob, (key, value) => {
    if (blacklist.includes(key)) {
      return undefined;
    }
    return value;
  });

  // Replace serialized function strings with actual function expressions
  const configData = replaceFunctions(configJson);

  // Build rule-descriptions.md
  const ruleTables = Object.keys(descriptionSections)
    .map(key => {
      const description = descriptionSections[key]!;

      return `
## ${description.title}

${description.intro ? description.intro : ''}

${
  description.rules.length
    ? descriptionTableHeader
    : '_There are no matching rules_'
}${description.rules
        .map(row => '| ' + row.join(' | ') + ' |')
        .join('\n')}`;
    })
    .join('\n\n');

  const descriptionsContent = `
<!--- This file is automatically generated using vite-plugin-axe-metadata --->

# Rule Descriptions

## Table of Contents
${TOC}
${ruleTables}`;

  return {
    configData,
    descriptions: descriptionsContent
  };
}

/**
 * Replace serialized function strings (from doT.template().toString()) with
 * actual function expressions in the JSON output.
 */
function replaceFunctions(jsonString: string): string {
  return jsonString
    .replace(
      /"(function anonymous\([\s\S]+?\) {)([\s\S]+?)(})"/g,
      m => JSON.parse(m) as string
    )
    .replace(
      /"(\(function \(\) {)([\s\S]+?)(}\)\(\))"/g,
      m => JSON.parse(m) as string
    );
}

// ---------------------------------------------------------------------------
// Part 3: default-config.ts generation
// ---------------------------------------------------------------------------

export function generateDefaultConfig(configData: string): string {
  return `// This file is automatically generated using vite-plugin-axe-metadata
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const defaultConfig: any = ${configData};

export default defaultConfig;
`;
}

// ---------------------------------------------------------------------------
// Plugin
// ---------------------------------------------------------------------------

export interface AxeMetadataPluginOptions {
  axeCoreRoot?: string;
}

export function axeMetadataPlugin(
  options?: AxeMetadataPluginOptions
): Plugin {
  const axeCoreRoot =
    options?.axeCoreRoot ?? process.cwd();

  return {
    name: 'vite-plugin-axe-metadata',
    enforce: 'pre',

    async buildStart() {
      // 1. Generate metadata-function-map.ts
      const functionMapContent = generateMetadataFunctionMap(axeCoreRoot);
      const functionMapPath = path.join(
        axeCoreRoot,
        'lib/core/base/metadata-function-map.ts'
      );
      fs.writeFileSync(functionMapPath, functionMapContent, 'utf-8');
      console.log(
        '[vite-plugin-axe-metadata] Generated metadata-function-map.ts'
      );

      // 2. Generate default-config.ts and rule-descriptions.md
      const { configData, descriptions } = generateConfig(axeCoreRoot);

      // Ensure generated directory exists
      const generatedDir = path.join(axeCoreRoot, 'lib/core/generated');
      fs.mkdirSync(generatedDir, { recursive: true });

      const defaultConfigPath = path.join(generatedDir, 'default-config.ts');
      fs.writeFileSync(
        defaultConfigPath,
        generateDefaultConfig(configData),
        'utf-8'
      );
      console.log(
        '[vite-plugin-axe-metadata] Generated default-config.ts'
      );

      // 3. Generate doc/rule-descriptions.md (formatted with Prettier)
      const docDir = path.join(axeCoreRoot, 'doc');
      fs.mkdirSync(docDir, { recursive: true });
      const descriptionsPath = path.join(docDir, 'rule-descriptions.md');

      // Format with Prettier to match the postbuild step
      let formattedDescriptions = descriptions;
      try {
        const prettier = await import('prettier');
        formattedDescriptions = await prettier.format(descriptions, {
          filepath: descriptionsPath
        });
      } catch {
        // If Prettier fails, write unformatted content
        console.warn(
          '[vite-plugin-axe-metadata] Prettier formatting failed, writing unformatted content'
        );
      }

      fs.writeFileSync(descriptionsPath, formattedDescriptions, 'utf-8');
      console.log(
        '[vite-plugin-axe-metadata] Generated rule-descriptions.md'
      );
    }
  };
}
