// This file is automatically generated using build/tasks/metadata-function-map.js
import hiddenContentEvaluate from '../../checks/visibility/hidden-content-evaluate';
import thHasDataCellsEvaluate from '../../checks/tables/th-has-data-cells-evaluate';
import tdHeadersAttrEvaluate from '../../checks/tables/td-headers-attr-evaluate';
import tdHasHeaderEvaluate from '../../checks/tables/td-has-header-evaluate';
import scopeValueEvaluate from '../../checks/tables/scope-value-evaluate';
import sameCaptionSummaryEvaluate from '../../checks/tables/same-caption-summary-evaluate';
import html5ScopeEvaluate from '../../checks/tables/html5-scope-evaluate';
import captionFakedEvaluate from '../../checks/tables/caption-faked-evaluate';
import svgNonEmptyTitleEvaluate from '../../checks/shared/svg-non-empty-title-evaluate';
import presentationalRoleEvaluate from '../../checks/shared/presentational-role-evaluate';
import nonEmptyIfPresentEvaluate from '../../checks/shared/non-empty-if-present-evaluate';
import isOnScreenEvaluate from '../../checks/shared/is-on-screen-evaluate';
import inlineStylePropertyEvaluate from '../../checks/shared/inline-style-property-evaluate';
import hasAltEvaluate from '../../checks/shared/has-alt-evaluate';
import existsEvaluate from '../../checks/shared/exists-evaluate';
import docHasTitleEvaluate from '../../checks/shared/doc-has-title-evaluate';
import avoidInlineSpacingEvaluate from '../../checks/shared/avoid-inline-spacing-evaluate';
import ariaLabelledbyEvaluate from '../../checks/shared/aria-labelledby-evaluate';
import ariaLabelEvaluate from '../../checks/shared/aria-label-evaluate';
import duplicateIdEvaluate from '../../checks/parsing/duplicate-id-evaluate';
import duplicateIdAfter from '../../checks/parsing/duplicate-id-after';
import uniqueFrameTitleEvaluate from '../../checks/navigation/unique-frame-title-evaluate';
import uniqueFrameTitleAfter from '../../checks/navigation/unique-frame-title-after';
import skipLinkEvaluate from '../../checks/navigation/skip-link-evaluate';
import regionEvaluate from '../../checks/navigation/region-evaluate';
import regionAfter from '../../checks/navigation/region-after';
import pAsHeadingEvaluate from '../../checks/navigation/p-as-heading-evaluate';
import metaRefreshEvaluate from '../../checks/navigation/meta-refresh-evaluate';
import internalLinkPresentEvaluate from '../../checks/navigation/internal-link-present-evaluate';
import identicalLinksSamePurposeEvaluate from '../../checks/navigation/identical-links-same-purpose-evaluate';
import identicalLinksSamePurposeAfter from '../../checks/navigation/identical-links-same-purpose-after';
import headingOrderEvaluate from '../../checks/navigation/heading-order-evaluate';
import headingOrderAfter from '../../checks/navigation/heading-order-after';
import targetSizeEvaluate from '../../checks/mobile/target-size-evaluate';
import targetOffsetEvaluate from '../../checks/mobile/target-offset-evaluate';
import metaViewportScaleEvaluate from '../../checks/mobile/meta-viewport-scale-evaluate';
import cssOrientationLockEvaluate from '../../checks/mobile/css-orientation-lock-evaluate';
import noAutoplayAudioEvaluate from '../../checks/media/no-autoplay-audio-evaluate';
import frameTestedEvaluate from '../../checks/media/frame-tested-evaluate';
import frameTestedAfter from '../../checks/media/frame-tested-after';
import captionEvaluate from '../../checks/media/caption-evaluate';
import structuredDlitemsEvaluate from '../../checks/lists/structured-dlitems-evaluate';
import onlyListitemsEvaluate from '../../checks/lists/only-listitems-evaluate';
import onlyDlitemsEvaluate from '../../checks/lists/only-dlitems-evaluate';
import listitemEvaluate from '../../checks/lists/listitem-evaluate';
import invalidChildrenEvaluate from '../../checks/lists/invalid-children-evaluate';
import dlitemEvaluate from '../../checks/lists/dlitem-evaluate';
import xmlLangMismatchEvaluate from '../../checks/language/xml-lang-mismatch-evaluate';
import validLangEvaluate from '../../checks/language/valid-lang-evaluate';
import hasLangEvaluate from '../../checks/language/has-lang-evaluate';
import landmarkIsUniqueEvaluate from '../../checks/landmarks/landmark-is-unique-evaluate';
import landmarkIsUniqueAfter from '../../checks/landmarks/landmark-is-unique-after';
import titleOnlyEvaluate from '../../checks/label/title-only-evaluate';
import multipleLabelEvaluate from '../../checks/label/multiple-label-evaluate';
import labelContentNameMismatchEvaluate from '../../checks/label/label-content-name-mismatch-evaluate';
import implicitEvaluate from '../../checks/label/implicit-evaluate';
import hiddenExplicitLabelEvaluate from '../../checks/label/hidden-explicit-label-evaluate';
import helpSameAsLabelEvaluate from '../../checks/label/help-same-as-label-evaluate';
import explicitEvaluate from '../../checks/label/explicit-evaluate';
import duplicateImgLabelEvaluate from '../../checks/label/duplicate-img-label-evaluate';
import altSpaceValueEvaluate from '../../checks/label/alt-space-value-evaluate';
import tabindexEvaluate from '../../checks/keyboard/tabindex-evaluate';
import noFocusableContentEvaluate from '../../checks/keyboard/no-focusable-content-evaluate';
import landmarkIsTopLevelEvaluate from '../../checks/keyboard/landmark-is-top-level-evaluate';
import frameFocusableContentEvaluate from '../../checks/keyboard/frame-focusable-content-evaluate';
import focusableNotTabbableEvaluate from '../../checks/keyboard/focusable-not-tabbable-evaluate';
import focusableNoNameEvaluate from '../../checks/keyboard/focusable-no-name-evaluate';
import focusableModalOpenEvaluate from '../../checks/keyboard/focusable-modal-open-evaluate';
import focusableElementEvaluate from '../../checks/keyboard/focusable-element-evaluate';
import focusableDisabledEvaluate from '../../checks/keyboard/focusable-disabled-evaluate';
import focusableContentEvaluate from '../../checks/keyboard/focusable-content-evaluate';
import accesskeysEvaluate from '../../checks/keyboard/accesskeys-evaluate';
import accesskeysAfter from '../../checks/keyboard/accesskeys-after';
import pageNoDuplicateEvaluate from '../../checks/generic/page-no-duplicate-evaluate';
import pageNoDuplicateAfter from '../../checks/generic/page-no-duplicate-after';
import matchesDefinitionEvaluate from '../../checks/generic/matches-definition-evaluate';
import hasTextContentEvaluate from '../../checks/generic/has-text-content-evaluate';
import hasDescendantEvaluate from '../../checks/generic/has-descendant-evaluate';
import hasDescendantAfter from '../../checks/generic/has-descendant-after';
import attrNonSpaceContentEvaluate from '../../checks/generic/attr-non-space-content-evaluate';
import autocompleteValidEvaluate from '../../checks/forms/autocomplete-valid-evaluate';
import autocompleteAppropriateEvaluate from '../../checks/forms/autocomplete-appropriate-evaluate';
import linkInTextBlockStyleEvaluate from '../../checks/color/link-in-text-block-style-evaluate';
import linkInTextBlockEvaluate from '../../checks/color/link-in-text-block-evaluate';
import colorContrastEvaluate from '../../checks/color/color-contrast-evaluate';
import validScrollableSemanticsEvaluate from '../../checks/aria/valid-scrollable-semantics-evaluate';
import unsupportedroleEvaluate from '../../checks/aria/unsupportedrole-evaluate';
import noImplicitExplicitLabelEvaluate from '../../checks/aria/no-implicit-explicit-label-evaluate';
import isElementFocusableEvaluate from '../../checks/aria/is-element-focusable-evaluate';
import invalidroleEvaluate from '../../checks/aria/invalidrole-evaluate';
import hasWidgetRoleEvaluate from '../../checks/aria/has-widget-role-evaluate';
import hasGlobalAriaAttributeEvaluate from '../../checks/aria/has-global-aria-attribute-evaluate';
import fallbackroleEvaluate from '../../checks/aria/fallbackrole-evaluate';
import deprecatedroleEvaluate from '../../checks/aria/deprecatedrole-evaluate';
import brailleRoledescriptionEquivalentEvaluate from '../../checks/aria/braille-roledescription-equivalent-evaluate';
import brailleLabelEquivalentEvaluate from '../../checks/aria/braille-label-equivalent-evaluate';
import ariaValidAttrValueEvaluate from '../../checks/aria/aria-valid-attr-value-evaluate';
import ariaValidAttrEvaluate from '../../checks/aria/aria-valid-attr-evaluate';
import ariaUnsupportedAttrEvaluate from '../../checks/aria/aria-unsupported-attr-evaluate';
import ariaRoledescriptionEvaluate from '../../checks/aria/aria-roledescription-evaluate';
import ariaRequiredParentEvaluate from '../../checks/aria/aria-required-parent-evaluate';
import ariaRequiredChildrenEvaluate from '../../checks/aria/aria-required-children-evaluate';
import ariaRequiredAttrEvaluate from '../../checks/aria/aria-required-attr-evaluate';
import ariaProhibitedAttrEvaluate from '../../checks/aria/aria-prohibited-attr-evaluate';
import ariaLevelEvaluate from '../../checks/aria/aria-level-evaluate';
import ariaHiddenBodyEvaluate from '../../checks/aria/aria-hidden-body-evaluate';
import ariaErrormessageEvaluate from '../../checks/aria/aria-errormessage-evaluate';
import ariaConditionalRowAttrEvaluate from '../../checks/aria/aria-conditional-row-attr-evaluate';
import ariaConditionalCheckboxAttrEvaluate from '../../checks/aria/aria-conditional-checkbox-attr-evaluate';
import ariaConditionalAttrEvaluate from '../../checks/aria/aria-conditional-attr-evaluate';
import ariaBusyEvaluate from '../../checks/aria/aria-busy-evaluate';
import ariaAllowedRoleEvaluate from '../../checks/aria/aria-allowed-role-evaluate';
import ariaAllowedAttrEvaluate from '../../checks/aria/aria-allowed-attr-evaluate';
import abstractroleEvaluate from '../../checks/aria/abstractrole-evaluate';
import xmlLangMismatchMatches from '../../rules/xml-lang-mismatch-matches';
import windowIsTopMatches from '../../rules/window-is-top-matches';
import widgetNotInlineMatches from '../../rules/widget-not-inline-matches';
import tableOrGridRoleMatches from '../../rules/table-or-grid-role-matches';
import svgNamespaceMatches from '../../rules/svg-namespace-matches';
import summaryInteractiveMatches from '../../rules/summary-interactive-matches';
import skipLinkMatches from '../../rules/skip-link-matches';
import scrollableRegionFocusableMatches from '../../rules/scrollable-region-focusable-matches';
import presentationRoleConflictMatches from '../../rules/presentation-role-conflict-matches';
import pAsHeadingMatches from '../../rules/p-as-heading-matches';
import objectIsLoadedMatches from '../../rules/object-is-loaded-matches';
import notHtmlMatches from '../../rules/not-html-matches';
import noRoleMatches from '../../rules/no-role-matches';
import noNegativeTabindexMatches from '../../rules/no-negative-tabindex-matches';
import noNamingMethodMatches from '../../rules/no-naming-method-matches';
import noExplicitNameRequiredMatches from '../../rules/no-explicit-name-required-matches';
import noEmptyRoleMatches from '../../rules/no-empty-role-matches';
import noAutoplayAudioMatches from '../../rules/no-autoplay-audio-matches';
import nestedInteractiveMatches from '../../rules/nested-interactive-matches';
import linkInTextBlockMatches from '../../rules/link-in-text-block-matches';
import layoutTableMatches from '../../rules/layout-table-matches';
import landmarkUniqueMatches from '../../rules/landmark-unique-matches';
import landmarkHasBodyContextMatches from '../../rules/landmark-has-body-context-matches';
import labelMatches from '../../rules/label-matches';
import labelContentNameMismatchMatches from '../../rules/label-content-name-mismatch-matches';
import isVisibleOnScreenMatches from '../../rules/is-visible-on-screen-matches';
import isVisibleMatches from '../../rules/is-visible-matches';
import isInitiatorMatches from '../../rules/is-initiator-matches';
import insertedIntoFocusOrderMatches from '../../rules/inserted-into-focus-order-matches';
import identicalLinksSamePurposeMatches from '../../rules/identical-links-same-purpose-matches';
import htmlNamespaceMatches from '../../rules/html-namespace-matches';
import headingMatches from '../../rules/heading-matches';
import hasImplicitChromiumRoleMatches from '../../rules/has-implicit-chromium-role-matches';
import frameTitleHasTextMatches from '../../rules/frame-title-has-text-matches';
import frameFocusableContentMatches from '../../rules/frame-focusable-content-matches';
import duplicateIdMiscMatches from '../../rules/duplicate-id-misc-matches';
import duplicateIdAriaMatches from '../../rules/duplicate-id-aria-matches';
import duplicateIdActiveMatches from '../../rules/duplicate-id-active-matches';
import dataTableMatches from '../../rules/data-table-matches';
import dataTableLargeMatches from '../../rules/data-table-large-matches';
import colorContrastMatches from '../../rules/color-contrast-matches';
import bypassMatches from '../../rules/bypass-matches';
import autocompleteMatches from '../../rules/autocomplete-matches';
import ariaRequiredParentMatches from '../../rules/aria-required-parent-matches';
import ariaRequiredChildrenMatches from '../../rules/aria-required-children-matches';
import ariaHiddenFocusMatches from '../../rules/aria-hidden-focus-matches';
import ariaHasAttrMatches from '../../rules/aria-has-attr-matches';
import ariaAllowedRoleMatches from '../../rules/aria-allowed-role-matches';
import ariaAllowedAttrMatches from '../../rules/aria-allowed-attr-matches';

const metadataFunctionMap = {
  'abstractrole-evaluate': abstractroleEvaluate,
  'accesskeys-after': accesskeysAfter,
  'accesskeys-evaluate': accesskeysEvaluate,
  'alt-space-value-evaluate': altSpaceValueEvaluate,
  'aria-allowed-attr-evaluate': ariaAllowedAttrEvaluate,
  'aria-allowed-attr-matches': ariaAllowedAttrMatches,
  'aria-allowed-role-evaluate': ariaAllowedRoleEvaluate,
  'aria-allowed-role-matches': ariaAllowedRoleMatches,
  'aria-busy-evaluate': ariaBusyEvaluate,
  'aria-conditional-attr-evaluate': ariaConditionalAttrEvaluate,
  'aria-conditional-checkbox-attr-evaluate':
    ariaConditionalCheckboxAttrEvaluate,
  'aria-conditional-row-attr-evaluate': ariaConditionalRowAttrEvaluate,
  'aria-errormessage-evaluate': ariaErrormessageEvaluate,
  'aria-has-attr-matches': ariaHasAttrMatches,
  'aria-hidden-body-evaluate': ariaHiddenBodyEvaluate,
  'aria-hidden-focus-matches': ariaHiddenFocusMatches,
  'aria-label-evaluate': ariaLabelEvaluate,
  'aria-labelledby-evaluate': ariaLabelledbyEvaluate,
  'aria-level-evaluate': ariaLevelEvaluate,
  'aria-prohibited-attr-evaluate': ariaProhibitedAttrEvaluate,
  'aria-required-attr-evaluate': ariaRequiredAttrEvaluate,
  'aria-required-children-evaluate': ariaRequiredChildrenEvaluate,
  'aria-required-children-matches': ariaRequiredChildrenMatches,
  'aria-required-parent-evaluate': ariaRequiredParentEvaluate,
  'aria-required-parent-matches': ariaRequiredParentMatches,
  'aria-roledescription-evaluate': ariaRoledescriptionEvaluate,
  'aria-unsupported-attr-evaluate': ariaUnsupportedAttrEvaluate,
  'aria-valid-attr-evaluate': ariaValidAttrEvaluate,
  'aria-valid-attr-value-evaluate': ariaValidAttrValueEvaluate,
  'attr-non-space-content-evaluate': attrNonSpaceContentEvaluate,
  'autocomplete-appropriate-evaluate': autocompleteAppropriateEvaluate,
  'autocomplete-matches': autocompleteMatches,
  'autocomplete-valid-evaluate': autocompleteValidEvaluate,
  'avoid-inline-spacing-evaluate': avoidInlineSpacingEvaluate,
  'braille-label-equivalent-evaluate': brailleLabelEquivalentEvaluate,
  'braille-roledescription-equivalent-evaluate':
    brailleRoledescriptionEquivalentEvaluate,
  'bypass-matches': bypassMatches,
  'caption-evaluate': captionEvaluate,
  'caption-faked-evaluate': captionFakedEvaluate,
  'color-contrast-evaluate': colorContrastEvaluate,
  'color-contrast-matches': colorContrastMatches,
  'css-orientation-lock-evaluate': cssOrientationLockEvaluate,
  'data-table-large-matches': dataTableLargeMatches,
  'data-table-matches': dataTableMatches,
  'deprecatedrole-evaluate': deprecatedroleEvaluate,
  'dlitem-evaluate': dlitemEvaluate,
  'doc-has-title-evaluate': docHasTitleEvaluate,
  'duplicate-id-active-matches': duplicateIdActiveMatches,
  'duplicate-id-after': duplicateIdAfter,
  'duplicate-id-aria-matches': duplicateIdAriaMatches,
  'duplicate-id-evaluate': duplicateIdEvaluate,
  'duplicate-id-misc-matches': duplicateIdMiscMatches,
  'duplicate-img-label-evaluate': duplicateImgLabelEvaluate,
  'exists-evaluate': existsEvaluate,
  'explicit-evaluate': explicitEvaluate,
  'fallbackrole-evaluate': fallbackroleEvaluate,
  'focusable-content-evaluate': focusableContentEvaluate,
  'focusable-disabled-evaluate': focusableDisabledEvaluate,
  'focusable-element-evaluate': focusableElementEvaluate,
  'focusable-modal-open-evaluate': focusableModalOpenEvaluate,
  'focusable-no-name-evaluate': focusableNoNameEvaluate,
  'focusable-not-tabbable-evaluate': focusableNotTabbableEvaluate,
  'frame-focusable-content-evaluate': frameFocusableContentEvaluate,
  'frame-focusable-content-matches': frameFocusableContentMatches,
  'frame-tested-after': frameTestedAfter,
  'frame-tested-evaluate': frameTestedEvaluate,
  'frame-title-has-text-matches': frameTitleHasTextMatches,
  'has-alt-evaluate': hasAltEvaluate,
  'has-descendant-after': hasDescendantAfter,
  'has-descendant-evaluate': hasDescendantEvaluate,
  'has-global-aria-attribute-evaluate': hasGlobalAriaAttributeEvaluate,
  'has-implicit-chromium-role-matches': hasImplicitChromiumRoleMatches,
  'has-lang-evaluate': hasLangEvaluate,
  'has-text-content-evaluate': hasTextContentEvaluate,
  'has-widget-role-evaluate': hasWidgetRoleEvaluate,
  'heading-matches': headingMatches,
  'heading-order-after': headingOrderAfter,
  'heading-order-evaluate': headingOrderEvaluate,
  'help-same-as-label-evaluate': helpSameAsLabelEvaluate,
  'hidden-content-evaluate': hiddenContentEvaluate,
  'hidden-explicit-label-evaluate': hiddenExplicitLabelEvaluate,
  'html-namespace-matches': htmlNamespaceMatches,
  'html5-scope-evaluate': html5ScopeEvaluate,
  'identical-links-same-purpose-after': identicalLinksSamePurposeAfter,
  'identical-links-same-purpose-evaluate': identicalLinksSamePurposeEvaluate,
  'identical-links-same-purpose-matches': identicalLinksSamePurposeMatches,
  'implicit-evaluate': implicitEvaluate,
  'inline-style-property-evaluate': inlineStylePropertyEvaluate,
  'inserted-into-focus-order-matches': insertedIntoFocusOrderMatches,
  'internal-link-present-evaluate': internalLinkPresentEvaluate,
  'invalid-children-evaluate': invalidChildrenEvaluate,
  'invalidrole-evaluate': invalidroleEvaluate,
  'is-element-focusable-evaluate': isElementFocusableEvaluate,
  'is-initiator-matches': isInitiatorMatches,
  'is-on-screen-evaluate': isOnScreenEvaluate,
  'is-visible-matches': isVisibleMatches,
  'is-visible-on-screen-matches': isVisibleOnScreenMatches,
  'label-content-name-mismatch-evaluate': labelContentNameMismatchEvaluate,
  'label-content-name-mismatch-matches': labelContentNameMismatchMatches,
  'label-matches': labelMatches,
  'landmark-has-body-context-matches': landmarkHasBodyContextMatches,
  'landmark-is-top-level-evaluate': landmarkIsTopLevelEvaluate,
  'landmark-is-unique-after': landmarkIsUniqueAfter,
  'landmark-is-unique-evaluate': landmarkIsUniqueEvaluate,
  'landmark-unique-matches': landmarkUniqueMatches,
  'layout-table-matches': layoutTableMatches,
  'link-in-text-block-evaluate': linkInTextBlockEvaluate,
  'link-in-text-block-matches': linkInTextBlockMatches,
  'link-in-text-block-style-evaluate': linkInTextBlockStyleEvaluate,
  'listitem-evaluate': listitemEvaluate,
  'matches-definition-evaluate': matchesDefinitionEvaluate,
  'meta-refresh-evaluate': metaRefreshEvaluate,
  'meta-viewport-scale-evaluate': metaViewportScaleEvaluate,
  'multiple-label-evaluate': multipleLabelEvaluate,
  'nested-interactive-matches': nestedInteractiveMatches,
  'no-autoplay-audio-evaluate': noAutoplayAudioEvaluate,
  'no-autoplay-audio-matches': noAutoplayAudioMatches,
  'no-empty-role-matches': noEmptyRoleMatches,
  'no-explicit-name-required-matches': noExplicitNameRequiredMatches,
  'no-focusable-content-evaluate': noFocusableContentEvaluate,
  'no-implicit-explicit-label-evaluate': noImplicitExplicitLabelEvaluate,
  'no-naming-method-matches': noNamingMethodMatches,
  'no-negative-tabindex-matches': noNegativeTabindexMatches,
  'no-role-matches': noRoleMatches,
  'non-empty-if-present-evaluate': nonEmptyIfPresentEvaluate,
  'not-html-matches': notHtmlMatches,
  'object-is-loaded-matches': objectIsLoadedMatches,
  'only-dlitems-evaluate': onlyDlitemsEvaluate,
  'only-listitems-evaluate': onlyListitemsEvaluate,
  'p-as-heading-evaluate': pAsHeadingEvaluate,
  'p-as-heading-matches': pAsHeadingMatches,
  'page-no-duplicate-after': pageNoDuplicateAfter,
  'page-no-duplicate-evaluate': pageNoDuplicateEvaluate,
  'presentation-role-conflict-matches': presentationRoleConflictMatches,
  'presentational-role-evaluate': presentationalRoleEvaluate,
  'region-after': regionAfter,
  'region-evaluate': regionEvaluate,
  'same-caption-summary-evaluate': sameCaptionSummaryEvaluate,
  'scope-value-evaluate': scopeValueEvaluate,
  'scrollable-region-focusable-matches': scrollableRegionFocusableMatches,
  'skip-link-evaluate': skipLinkEvaluate,
  'skip-link-matches': skipLinkMatches,
  'structured-dlitems-evaluate': structuredDlitemsEvaluate,
  'summary-interactive-matches': summaryInteractiveMatches,
  'svg-namespace-matches': svgNamespaceMatches,
  'svg-non-empty-title-evaluate': svgNonEmptyTitleEvaluate,
  'tabindex-evaluate': tabindexEvaluate,
  'table-or-grid-role-matches': tableOrGridRoleMatches,
  'target-offset-evaluate': targetOffsetEvaluate,
  'target-size-evaluate': targetSizeEvaluate,
  'td-has-header-evaluate': tdHasHeaderEvaluate,
  'td-headers-attr-evaluate': tdHeadersAttrEvaluate,
  'th-has-data-cells-evaluate': thHasDataCellsEvaluate,
  'title-only-evaluate': titleOnlyEvaluate,
  'unique-frame-title-after': uniqueFrameTitleAfter,
  'unique-frame-title-evaluate': uniqueFrameTitleEvaluate,
  'unsupportedrole-evaluate': unsupportedroleEvaluate,
  'valid-lang-evaluate': validLangEvaluate,
  'valid-scrollable-semantics-evaluate': validScrollableSemanticsEvaluate,
  'widget-not-inline-matches': widgetNotInlineMatches,
  'window-is-top-matches': windowIsTopMatches,
  'xml-lang-mismatch-evaluate': xmlLangMismatchEvaluate,
  'xml-lang-mismatch-matches': xmlLangMismatchMatches
};

export default metadataFunctionMap;
